// packages/vue3/sampleApp/App.vue
<template>
  <div>
    <AdvancedImage :cldImg="cldImg" :plugins="plugins" />
  </div>
  <div>
    <AdvancedVideo url="https://res.cloudinary.com/demo/video/upload/dog.mp4" />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import {
  AdvancedImage,
  AdvancedVideo,
  accessibility,
  responsive,
  lazyload,
  placeholder,
} from "../src";
import { CloudinaryImage } from "@cloudinary/url-gen/assets/CloudinaryImage";

export default defineComponent({
  name: "App",
  components: {
    AdvancedImage,
    AdvancedVideo,
  },
  setup(props) {
    const cldImg = new CloudinaryImage(
      "sample",
      { cloudName: "demo" },
      { analytics: false }
    );

    const plugins = [responsive({ steps: 100 })];

    return {
      cldImg,
      plugins,
    };
  },
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// packages/react/playground/src/App.tsx
import React from 'react'
import './App.css'
import {
  AdvancedImage,
  accessibility,
  responsive,
  lazyload,
  placeholder
} from '@cloudinary/react/src'
import { CloudinaryImage } from '@cloudinary/url-gen/assets/CloudinaryImage'

// This is our playground and can be used to test library
function App() {
  const img = new CloudinaryImage('sample', { cloudName: 'demo' })

  return (
    <div>
      <AdvancedImage cldImg={img} plugins={[responsive({ steps: 100 })]} />
    </div>
  )
}

export default App
