// frameworks/react/test-app/src/App.tsx
import React, {Fragment, useState} from 'react'
import {AdvancedImage, accessibility, responsive, lazyload, placeholder} from '@cloudinary/react';
import {CloudinaryImage} from "@cloudinary/base/assets/CloudinaryImage";

const tests = [
  'responsive',
  'placeholder',
  'lazy',
  'lazyPlaceholder',
  'lazyResponsive',
  'responsivePlaceholder'
];

const App = () => {
  let img = new CloudinaryImage('sample', {cloudName: 'demo'});
  const [test, setTest]: [any, any] = useState(0);

  const Buttons = () => (
    <Fragment>
      {
        tests.map((t, i) =>
          <button key={"btn-" + i} id={t + 'Btn'} onClick={() => setTest(t)}>{t + ' test'}</button>
        )
      }
    </Fragment>
  );

  return (
    <div id="top">
      <Buttons/>
      {test === 'responsive' &&
      <Fragment>
        <h1>Responsive Image</h1>
        <div style={{width: "330px"}}>
          <AdvancedImage cldImg={img} plugins={[responsive(100)]}/>
        </div>
      </Fragment>
      }
    </div>
  );
}

export default App;

// frameworks/svelte/example/src/App.svelte
<script lang="ts">
  import {AdvancedImage, responsive, lazyload, placeholder, accessibility} from '@cloudinary/svelte';
  import {CloudinaryImage} from "@cloudinary/base";

  export let text: string;

  const img = new CloudinaryImage('sample', {cloudName: 'demo'});
</script>

<main>
    <div class="title-container">
        <h1 class="title">Cloudinary Svelte Example</h1>
        <p class="text">{text}</p>
        <p class="text">&#8595;</p>
    </div>
    <div>
        <AdvancedImage class="image" cldImg={img} plugins={[lazyload(),responsive(), accessibility(), placeholder()]}/>
    </div>
</main>

<style>
    .title-container {
        text-align: center;
        padding: 1em;
        max-width: 440px;
        margin: 0 auto;
        height: 2000px;
    }

    .title {
        color: #ff3e00;
        text-transform: uppercase;
        font-size: 4em;
        font-weight: 100;
    }

    .text {
        color: darkslateblue;
        font-size: 2em;
    }

    :global(.image) {
        width: 100%;
    }
</style>
