// packages/html/frameworks/svelte/example-ts/src/App.svelte
<script lang="ts">
  import {AdvancedImage, responsive, lazyload, placeholder, accessibility} from '@cloudinary/svelte/dist/';
  import {CloudinaryImage} from "@cloudinary/url-gen";

  export let text: string;

  const img = new CloudinaryImage('sample', {cloudName: 'demo'});
</script>

<main>
    <div class="title-container">
        <h1 class="title">Cloudinary Svelte Example</h1>
        <p class="text">{text}</p>
        <p class="text">&#8595;</p>
    </div>
    <div>
        <AdvancedImage class="image" cldImg={img} plugins={[lazyload(),responsive(), accessibility(), placeholder()]}/>
    </div>
</main>

<style>
    .title-container {
        text-align: center;
        padding: 1em;
        max-width: 440px;
        margin: 0 auto;
        height: 2000px;
    }

    .title {
        color: #ff3e00;
        text-transform: uppercase;
        font-size: 4em;
        font-weight: 100;
    }

    .text {
        color: darkslateblue;
        font-size: 2em;
    }

    :global(.image) {
        width: 100%;
    }
</style>

// packages/vue3/src/App.vue
<template>
  <div>
    <AdvancedImage :cldImg="img" :plugins="[responsive(100)]" />
  </div>
  <div>
    <AdvancedVideo url="https://res.cloudinary.com/demo/video/upload/dog.mp4" />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import {
  AdvancedImage,
  AdvancedVideo,
  accessibility,
  responsive,
  lazyload,
  placeholder,
} from "./index";
import { CloudinaryImage } from "@cloudinary/url-gen/assets/CloudinaryImage";

export default defineComponent({
  name: "App",
  components: {
    AdvancedImage,
    AdvancedVideo,
  },
  setup(props) {
    const img = new CloudinaryImage("sample", { cloudName: "demo" });

    return {
      img,
      responsive,
    };
  },
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
